"""baseline schema

Adopts Alembic on the existing create_all database. The schema is defined by the
SQLAlchemy models (single source of truth in app/models.py), so this baseline
provisions a FRESH database by running create_all for every model table + index.

An EXISTING database (already built by create_all — e.g. the live Neon DB) is
brought under Alembic control with `alembic stamp head`, which records this
revision WITHOUT running any DDL. From here on, schema changes get their own
autogenerated migrations (`alembic revision --autogenerate -m "..."`), replacing
the ad-hoc "ADD COLUMN IF NOT EXISTS" statements in app/db.py.

Revision ID: 9fc6f7511aa9
Revises:
Create Date: 2026-08-22
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa: F401 — kept for parity with autogenerated files

revision: str = "9fc6f7511aa9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Provision the full schema from the models (fresh DBs only). No-op in
    practice on an already-populated DB brought in via `alembic stamp head`."""
    bind = op.get_bind()
    # Self-contained: the schema + pgvector must exist before the (schema-qualified,
    # Vector-typed) tables are created. Idempotent, and also covers offline --sql.
    bind.exec_driver_sql("CREATE SCHEMA IF NOT EXISTS wiora")
    bind.exec_driver_sql("CREATE EXTENSION IF NOT EXISTS vector")

    from app.db import Base
    from app import models  # noqa: F401 — register every model on Base.metadata

    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    """Drop every model table. Never run against a database holding real data."""
    from app.db import Base
    from app import models  # noqa: F401

    Base.metadata.drop_all(bind=op.get_bind())
